apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mongo
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: "localhost:27017"
  - name: databaseName
    value: tag
  - name: collectionName
    value: auctions
