apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: auction-statestore
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: "auction-db:27017"
  - name: databaseName
    value: tag
  - name: collectionName
    value: auctions
scopes:
- auction-api
