apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: "cache"
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: session-api-redis:6379
  - name: redisPassword
    value: ""